architecture:
  dtype:
    param: float32
    activation: bfloat16
  rope: true
  vocab_size: 100288
  dropout: 0.0
  bias: true
  block_size: 2048
  n_layers: 10
  n_embd: 2048
  n_head: 16
  layer_norm_eps: 1.0e-05
  intermediate_size: -1
  moe:
    experts: 8
    experts_per_embd: 2
    capacity_factor: 1.0
    capacity_round_to: 128
    implementation: base
    bias_update_rate: 0.25
    bias_smoothing: 1.0
optimization:
  lr: 0.0003
  weight_decay: 0.1
  warmup_pct: 0.01
  decay_pct: 0.01
  constant_pct: 0.02
  schedule: wsd_reset
  reset_optimizer: true
  lora:
    rank: 16
    alpha: 16.0
    target_modules:
    - kernel
training:
  batch_size: 512
  per_device_batch_size: -1
  tokens:
  - 16000000000
  - 1600000000
  - 400000000
  - 1600000000
  - 400000000
  dataset:
  - - name: pile_detoxify
      rate: 1.0
      style: PMD
  - - name: harmfulqa
      rate: 0.5
      style: PADDED
      suffix: red_2048
    - name: mmlu
      rate: 0.5
      style: PADDED
      suffix: '2048'
  - - name: harmfulqa
      rate: 1.0
      style: PADDED
      suffix: blue_2048
  - - name: harmfulqa
      rate: 0.5
      style: PADDED
      suffix: red_2048
    - name: squad
      rate: 0.5
      style: PADDED
      suffix: '2048'
  - - name: harmfulqa
      rate: 1.0
      style: PADDED
      suffix: blue_2048
  validation: false
  evaluate: true
  validation_steps: 2048
  skip_first_dataset_validation: true
  fade:
    overlap: 0.0
    curve: linear
eval:
  evaluations:
  - mmlu
  - squad
  - pile_ppl
logging:
  report_interval: 32
  checkpoint_interval: 3814
  validation_interval: 76
  wandb: true
  plots:
    save: true
job: continual/train/benchmark_moe_lora
request:
  chip: h200
  min_chips: 4
  n_shards: 1
