"""
Theseus remote bootstrap - generated by dispatch()
"""
# mypy: ignore-errors

import json
from loguru import logger
from omegaconf import OmegaConf
from theseus.config import configuration
from theseus.registry import JOBS
from theseus.job import RestoreableJob
from theseus.base.job import ExecutionSpec
from theseus.base.hardware import HardwareResult, Cluster, ClusterMachine
from theseus.base.chip import SUPPORTED_CHIPS
from theseus.base.topology import Topology

# === EMBEDDED DATA (filled by dispatch.py) ===
CONFIG_YAML = """__CONFIG_YAML__"""
HARDWARE_JSON = """__HARDWARE_JSON__"""
JOB_NAME = "__JOB_NAME__"
PROJECT = "__PROJECT__"
GROUP = "__GROUP__"


def _reconstruct_hardware(data: dict) -> HardwareResult:
    """Reconstruct HardwareResult from serialized JSON."""
    chip = SUPPORTED_CHIPS.get(data["chip"]) if data["chip"] else None
    hosts = []
    for h in data["hosts"]:
        cluster = Cluster(
            name=h["cluster"]["name"],
            root=h["cluster"]["root"],
            work=h["cluster"]["work"],
        )
        resources = {
            SUPPORTED_CHIPS[k]: v
            for k, v in h["resources"].items()
            if k in SUPPORTED_CHIPS
        }
        hosts.append(
            ClusterMachine(name=h["name"], cluster=cluster, resources=resources)
        )
    return HardwareResult(chip=chip, hosts=hosts, total_chips=data["total_chips"])


def main():
    cfg = OmegaConf.create(CONFIG_YAML)
    hardware = _reconstruct_hardware(json.loads(HARDWARE_JSON))

    topology = Topology.new(hardware.chip) if hardware.chip else None
    spec = ExecutionSpec(
        name=JOB_NAME,
        project=PROJECT or None,
        group=GROUP or None,
        hardware=hardware,
        topology=topology,
        distributed=len(hardware.hosts) > 1,
    )

    job_key = cfg.job
    if job_key not in JOBS:
        raise RuntimeError(
            f"Job '{job_key}' not in registry. Available: {list(JOBS.keys())}"
        )

    job_cls = JOBS[job_key]

    # Check for existing checkpoint if job is restorable (idempotent dispatch)
    if issubclass(job_cls, RestoreableJob):
        latest = RestoreableJob.latest(spec)
        if latest:
            logger.info(f"DISPATCH | restoring from checkpoint: {latest}")
            job, cfg = RestoreableJob.from_checkpoint(latest, spec)
            with configuration(cfg):
                job()
            return

    # No checkpoint found, start fresh
    logger.info(f"DISPATCH | starting new job: {job_key}")
    with configuration(cfg):
        job = job_cls(spec)
        job()


if __name__ == "__main__":
    main()
