"""
Theseus remote bootstrap - generated by dispatch()

Supports automatic batch size rightsizing when per_device_batch_size = -1.
"""
# mypy: ignore-errors

import json
import os
import subprocess
import sys
import time
from loguru import logger
from omegaconf import OmegaConf

# === EMBEDDED DATA (filled by dispatch.py) ===
CONFIG_YAML = """__CONFIG_YAML__"""
HARDWARE_JSON = """__HARDWARE_JSON__"""
JOB_NAME = "__JOB_NAME__"
PROJECT = "__PROJECT__"
GROUP = "__GROUP__"
RIGHTSIZING_ENABLED = __RIGHTSIZING_ENABLED__  # noqa: F821

# === RIGHTSIZING CONSTANTS ===
BATCH_SIZES = [128, 64, 32, 16, 10, 8, 4, 3, 2, 1]
BATCH_SIZE_ENV_VAR = "THESEUS_BATCH_SIZE_OVERRIDE"
RIGHTSIZING_PROBE_VAR = "THESEUS_RIGHTSIZING_PROBE"  # "1" = probe mode
INITIAL_TIMEOUT = 600  # 10 minutes


def setup_logging(verbose: bool = False) -> None:
    """Configure loguru with appropriate log level."""
    logger.remove()
    logger.add(
        sys.stderr,
        format="<cyan>{time:YYYY-MM-DD HH:mm:ss}</cyan> |"
        "<level>{level: ^8}</level>| "
        "<magenta>({name}:{line})</magenta> <level>{message}</level>",
        level="DEBUG" if verbose else "INFO",
        colorize=True,
        enqueue=True,
        filter=lambda x: x["extra"].get("task", "") != "plot",
    )


def rightsizing_search() -> None:
    """Search for working batch size via subprocess probes."""
    setup_logging()
    logger.info("RIGHTSIZING | starting batch size search")

    timeout = INITIAL_TIMEOUT  # 10 minutes initially

    for bs in BATCH_SIZES:
        logger.info(f"RIGHTSIZING | probing batch_size={bs} (timeout={timeout}s)")

        env = os.environ.copy()
        env[BATCH_SIZE_ENV_VAR] = str(bs)
        env[RIGHTSIZING_PROBE_VAR] = "1"  # Probe mode: disable wandb

        start_time = time.time()
        try:
            result = subprocess.run(
                [sys.executable, __file__],
                env=env,
                capture_output=True,
                text=True,
                timeout=timeout,
            )
        except subprocess.TimeoutExpired:
            # Survived the timeout - this batch size works!
            logger.info(f"RIGHTSIZING | batch_size={bs} survived {timeout}s - SUCCESS")
            logger.info(f"RIGHTSIZING | starting real run with batch_size={bs}")
            # Start real run (without probe mode, with wandb)
            run_real_job(bs)
            return

        elapsed = time.time() - start_time

        # Check for OOM
        combined = result.stdout + result.stderr
        if "RESOURCE_EXHAUSTED" in combined:
            logger.warning(f"RIGHTSIZING | OOM at batch_size={bs} after {elapsed:.1f}s")
            # Update timeout: next attempt uses 2x this crash time
            timeout = max(elapsed * 2, 60)  # at least 60 seconds
            logger.info(f"RIGHTSIZING | new timeout={timeout:.1f}s")
            continue

        # Non-OOM error - propagate
        logger.error(f"RIGHTSIZING | non-OOM error at batch_size={bs}")
        if result.stdout:
            sys.stdout.write(result.stdout)
        if result.stderr:
            sys.stderr.write(result.stderr)
        sys.exit(result.returncode)

    logger.error("RIGHTSIZING | FAILED - all batch sizes exhausted")
    sys.exit(1)


def run_real_job(batch_size: int) -> None:
    """Start the real job run (not a probe) with wandb enabled."""
    env = os.environ.copy()
    env[BATCH_SIZE_ENV_VAR] = str(batch_size)
    # No RIGHTSIZING_PROBE_VAR = wandb stays enabled

    result = subprocess.run(
        [sys.executable, __file__],
        env=env,
    )
    sys.exit(result.returncode)


def run_job(batch_size_override: int | None) -> None:
    """Run the actual job. JAX imports happen here."""
    from theseus.config import configuration
    from theseus.registry import JOBS
    from theseus.job import RestoreableJob
    from theseus.base.job import ExecutionSpec
    from theseus.base.topology import Topology

    setup_logging()
    cfg = OmegaConf.create(CONFIG_YAML)

    # Check if we're in probe mode
    is_probe = os.environ.get(RIGHTSIZING_PROBE_VAR) == "1"

    # Apply batch size override
    if batch_size_override is not None:
        logger.info(f"RIGHTSIZING | using batch_size={batch_size_override}")
        OmegaConf.update(cfg, "training.per_device_batch_size", batch_size_override)

    # Disable wandb in probe mode
    if is_probe:
        if OmegaConf.select(cfg, "logging.wandb") is not None:
            logger.info("RIGHTSIZING | probe mode - disabling wandb")
            OmegaConf.update(cfg, "logging.wandb", False)

    # Reconstruct hardware from embedded JSON
    hardware = _reconstruct_hardware(json.loads(HARDWARE_JSON))

    topology = Topology.new(hardware.chip) if hardware.chip else None
    spec = ExecutionSpec(
        name=JOB_NAME,
        project=PROJECT or None,
        group=GROUP or None,
        hardware=hardware,
        topology=topology,
        distributed=len(hardware.hosts) > 1,
    )

    job_key = cfg.job
    if job_key not in JOBS:
        raise RuntimeError(
            f"Job '{job_key}' not in registry. Available: {list(JOBS.keys())}"
        )

    job_cls = JOBS[job_key]

    # Check for existing checkpoint if job is restorable (idempotent dispatch)
    if issubclass(job_cls, RestoreableJob):
        latest = RestoreableJob.latest(spec)
        if latest:
            logger.info(f"DISPATCH | restoring from checkpoint: {latest}")
            job, cfg = RestoreableJob.from_checkpoint(latest, spec)
            with configuration(cfg):
                job()
            return

    # No checkpoint found, start fresh
    logger.info(f"DISPATCH | starting new job: {job_key}")
    with configuration(cfg):
        job = job_cls(spec)
        job()


def _reconstruct_hardware(data: dict) -> "HardwareResult":  # noqa: F821
    """Reconstruct HardwareResult from serialized JSON."""
    from theseus.base.hardware import HardwareResult, Cluster, ClusterMachine
    from theseus.base.chip import SUPPORTED_CHIPS

    chip = SUPPORTED_CHIPS.get(data["chip"]) if data["chip"] else None
    hosts = []
    for h in data["hosts"]:
        cluster = Cluster(
            name=h["cluster"]["name"],
            root=h["cluster"]["root"],
            work=h["cluster"]["work"],
        )
        resources = {
            SUPPORTED_CHIPS[k]: v
            for k, v in h["resources"].items()
            if k in SUPPORTED_CHIPS
        }
        hosts.append(
            ClusterMachine(name=h["name"], cluster=cluster, resources=resources)
        )
    return HardwareResult(chip=chip, hosts=hosts, total_chips=data["total_chips"])


def main():
    batch_size_override = os.environ.get(BATCH_SIZE_ENV_VAR)

    if batch_size_override is not None:
        # Child process (probe or real run)
        run_job(int(batch_size_override))
    elif RIGHTSIZING_ENABLED:
        # Parent process - search
        rightsizing_search()
    else:
        # Normal execution
        run_job(None)


if __name__ == "__main__":
    main()
