architecture:
  dtype:
    param: float32
    activation: bfloat16
  n_embd: 1024
  n_layers: 16
  bias: true
  dropout: 0.0
  n_head: 16
  block_size: 512
  max_block_size: 1024
  use_fork_channel: true
  rope: true
  vocab_size: 100288
  fork:
  - 3
  - 6
  - 9
  layer_norm_eps: 1.0e-05
  intermediate_size: -1
eval:
  evaluations:
  - blimp
tokenizer:
  backend: tiktoken
  name: cl100k_base
  huggingface:
    use_fast: true
    use_remote_code: false
logging:
  plots:
    save: false
  report_interval: 32
  checkpoint_interval: 16384
  validation_interval: 2048
  wandb: true
optimization:
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  lr: 0.0003
  warmup_pct: 0.005
  decay_pct: 0.01
training:
  batch_size: 512
  per_device_batch_size: -1
  tokens: 40000000000
  warmup_pct: 0.01
  decay_pct: 0.1
  validation: true
  evaluate: false
  dataset:
  - name: fineweb
    rate: 1.0
    style: PMD
    suffix: ''
  validation_steps: 2048
job: scratchbubbles/train/pretrain
request:
  n_shards: 1
