architecture:
  dtype:
    param: float32
    activation: bfloat16
  vocab_size: 100288
  dropout: 0.0
  block_size: 2048
  n_layers: 48
  n_embd: 1024
  d_state: 128
  d_conv: 4
  expand: 2
  n_groups: 1
  n_heads: -1
optimization:
  lr: 0.0003
  weight_decay: 0.1
  warmup_pct: 0.01
  decay_pct: 0.01
  constant_pct: 0.02
  schedule: cosine_rewarm
  reset_optimizer: false
training:
  batch_size: 512
  per_device_batch_size: -1
  tokens:
  - 11200000000
  - 1120000000
  - 280000000
  - 1120000000
  - 280000000
  dataset:
  - - name: pile_detoxify
      rate: 1.0
      style: PMD
  - - name: harmfulqa
      rate: 0.5
      style: PADDED
      suffix: red
    - name: mmlu
      rate: 0.5
      style: PADDED
  - - name: harmfulqa
      rate: 1.0
      style: PADDED
      suffix: blue
  - - name: harmfulqa
      rate: 0.5
      style: PADDED
      suffix: red
    - name: squad
      rate: 0.5
      style: PADDED
  - - name: harmfulqa
      rate: 1.0
      style: PADDED
      suffix: blue
  validation: false
  evaluate: true
  validation_steps: 2048
  skip_first_dataset_validation: true
  fade:
    overlap: 0.0
    curve: linear
eval:
  evaluations:
  - mmlu
  - squad
  - pile
logging:
  report_interval: 32
  checkpoint_interval: 133
  validation_interval: 53
  wandb: true
job: continual/train/benchmark_mamba
request:
  chip: h200
  min_chips: 4
  n_shards: 1
