job: backbone/evaluate
architecture:
  backbone:
    implementation: qwen
    weights: Qwen/Qwen2.5-1.5B-Instruct
  dtype:
    param: float32
    activation: bfloat16
  block_size: 2048
tokenizer:
  backend: huggingface
  name: Qwen/Qwen2.5-1.5B-Instruct
  huggingface:
    use_fast: true
    use_remote_code: false
training:
  per_device_batch_size: 16
eval:
  length: -1
  evaluations:
    # ds_nlu
    - mnli
    - qqp
    - sst2
    - siqa
    # ds_domain
    - fineweb_ppl
    - pes2o_ppl
    - pile_ppl
    - tinystories_ppl
    # ds_multilingual
    - ccaligned_fr_ppl
    - ccaligned_de_ppl
    - ccaligned_zh_ppl
    # cg_grammar
    - mtob
    # cg_cfq
    - cfq
    # cg_safety
    - mmlu
    - squad
request:
  chip: h100
  min_chips: 2
  n_shards: 1
