architecture:
  dtype:
    param: float32
    activation: bfloat16
  rope: true
  vocab_size: 100288
  dropout: 0.0
  bias: true
  block_size: 2048
  n_layers: 24
  n_embd: 2048
  n_head: 16
  mamba_layers: even
  d_state: 128
  d_conv: 4
  expand: 2
  n_groups: 1
  n_heads: -1
optimization:
  lr: 0.0003
  weight_decay: 0.1
  warmup_pct: 0.01
  decay_pct: 0.01
  constant_pct: 0.02
  schedule: wsd_reset
  reset_optimizer: true
training:
  batch_size: 512
  per_device_batch_size: -1
  tokens:
  - 10000000000
  - 10000000000
  dataset:
  - - name: fineweb
      rate: 1.0
      style: PMD
  - - name: pes2o
      rate: 1.0
      style: PMD
  validation: false
  evaluate: true
  validation_steps: 2048
  skip_first_dataset_validation: false
  fade:
    overlap: 0.1
    curve: cosine
eval:
  evaluations:
  - fineweb_ppl
  - pes2o
  - pile
  - tinystories
logging:
  report_interval: 32
  checkpoint_interval: 1000000000
  validation_interval: 1907
  wandb: true
  plots:
    save: true
job: continual/train/benchmark_hybrid
request:
  chip: h200
  min_chips: 4
  n_shards: 1
