#!/usr/bin/env python3
"""Emit a markdown file with one `theseus submit` command per generated config.

The command shape is:
    uv run theseus submit <name> <stage1.yaml> -s <stage2.yaml> ... -s <training.yaml> \\
      --env XLA_PYTHON_CLIENT_PREALLOCATE=false \\
      --cluster microsoft --chip h100 -n 4 --n_shards 2 \\
      -p continual -g <split>_<scale> training.per_device_batch_size=1

The first positional YAML and every `-s` flag are pipeline stages in order;
tokenization comes first, training is the LAST `-s`. Stages are deduped per
dataset entry (PADDED and PMD both go through their own tokenize config).

Usage:
    uv run python scripts/generate_launch_commands.py
"""

from pathlib import Path

import yaml


CLUSTER = "microsoft"
CHIP = "h100"
N_CHIPS = 4
N_SHARDS = 2
PROJECT = "continual"
ENV_FLAGS = "--env XLA_PYTHON_CLIENT_PREALLOCATE=false"
EXTRA = "training.per_device_batch_size=1"
DATA_DIR = Path("configs/data/cl100k")


def _data_config_for(entry: dict) -> str | None:
    """Map a training.dataset entry to its tokenize YAML path (relative to repo).

    PADDED entries have a `_{block_size}` suffix already baked in by the
    benchmark generator; their tokenize config filename mirrors the on-disk
    suffix: configs/data/cl100k/{name}_{suffix}.yaml.

    PMD entries use suffix-agnostic tokenize configs (the PMD stream is a flat
    token buffer, not block-size-specific); we prefer a suffix-specific
    variable tokenize config if it exists, otherwise fall back to the bare
    {name}.yaml. Missing configs return None (caller may flag).
    """
    name = entry["name"]
    suffix = entry.get("suffix", "")
    if suffix:
        cand = DATA_DIR / f"{name}_{suffix}.yaml"
    else:
        cand = DATA_DIR / f"{name}.yaml"
    if cand.exists():
        return str(cand)
    if suffix:
        # Fall back to name-only tokenize config for PMD variants where the
        # suffix-specific file is missing.
        fallback = DATA_DIR / f"{name}.yaml"
        if fallback.exists():
            return str(fallback)
    return None


def _stages_for(training_yaml: Path) -> tuple[list[str], list[str]]:
    """Return (stage_paths, missing_names) for a training config.

    Only PADDED entries become per-run tokenize stages, since their artifacts
    are block-size specific and cheap to materialize. PMD datasets are big
    streaming pretraining corpora (fineweb, pile, ccaligned, etc.) that must
    be tokenized once out-of-band — running them as `-s` stages on every
    training submission would re-check massive corpora on every run.
    """
    cfg = yaml.safe_load(training_yaml.read_text())
    datasets = cfg.get("training", {}).get("dataset", [])
    stages: list[str] = []
    missing: list[str] = []
    seen: set[str] = set()
    for stage in datasets:
        for entry in stage:
            if entry.get("style") != "PADDED":
                continue
            path = _data_config_for(entry)
            if path is None:
                missing.append(
                    f"{entry['name']}"
                    + (f"_{entry['suffix']}" if entry.get("suffix") else "")
                )
                continue
            if path not in seen:
                seen.add(path)
                stages.append(path)
    return stages, missing


def main() -> None:
    repo_root = Path(__file__).parent.parent
    configs_root = repo_root / "configs" / "continual"
    out_path = repo_root / "docs" / "launch_commands.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# Launch commands",
        "",
        "Auto-generated by `scripts/generate_launch_commands.py`. Do not hand-edit.",
        "",
        "Stage order is `<first_stage> -s <stage_2> ... -s <training>`. The last",
        "`-s` is the training config; everything before it is tokenization.",
        "",
    ]

    all_missing: set[str] = set()
    total = 0

    splits = sorted(p.name for p in configs_root.iterdir() if p.is_dir())
    for split in splits:
        split_dir = configs_root / split
        scales = sorted(p.name for p in split_dir.iterdir() if p.is_dir())
        for scale in scales:
            scale_dir = split_dir / scale
            group = f"{split}_{scale}"
            lines.append(f"## {split} / {scale}")
            lines.append("")
            lines.append("```bash")
            for cfg_path in sorted(scale_dir.glob("*.yaml")):
                name = cfg_path.stem
                rel_training = cfg_path.relative_to(repo_root)
                data_stages, missing = _stages_for(cfg_path)
                all_missing.update(missing)

                # Full stage list, training last.
                full_stages = [
                    str(rel_training.parent.parent.parent.parent / s) if False else s
                    for s in data_stages
                ]
                full_stages = data_stages + [str(rel_training)]

                first = full_stages[0]
                rest = full_stages[1:]
                rest_flags = " ".join(f"-s {s}" for s in rest)
                rest_part = f" {rest_flags}" if rest_flags else ""
                lines.append(
                    f"uv run theseus submit {name} {first}{rest_part} "
                    f"{ENV_FLAGS} --cluster {CLUSTER} --chip {CHIP} "
                    f"-n {N_CHIPS} --n_shards {N_SHARDS} "
                    f"-p {PROJECT} -g {group} {EXTRA}"
                )
                total += 1
            lines.append("```")
            lines.append("")

    if all_missing:
        lines.append("## Missing tokenize configs")
        lines.append("")
        lines.append(
            "The following dataset entries had no matching tokenize YAML under "
            "`configs/data/cl100k/`. Launch commands fell back to the bare "
            "`{name}.yaml` where available, but these are worth auditing:"
        )
        lines.append("")
        for m in sorted(all_missing):
            lines.append(f"- `{m}`")
        lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"Wrote {total} launch commands to {out_path}")
    if all_missing:
        print(f"  ({len(all_missing)} unique missing tokenize configs — see doc)")


if __name__ == "__main__":
    main()
