#!/usr/bin/env bash
#
# Launch all 1b `_shuffled` continual runs (lact, moe, transformer, mamba)
# across the splits with permuted stage order:
#   - ds_domain        (pes2o -> fineweb)
#   - ds_multilingual  (zh -> de -> fr)
#   - cg_safety        (pile_detoxify -> red+squad -> blue -> red+mmlu -> blue)
#
# Each job uses:
#   - 4x B200 GPUs on the bonete cluster
#   - 32 CPUs, 512G memory
#   - tensor-parallel shards: 1
#   - per-device batch size: 2
#
# Usage:
#   bash scripts/launch_shuffled_1b.sh        # launch all
#   bash scripts/launch_shuffled_1b.sh --dry  # print commands only
#
# Auto-generated by scripts/generate_launch_commands.py. Do not hand-edit.

DRY_RUN=false
if [[ "${1:-}" == "--dry" ]]; then
    DRY_RUN=true
    echo "=== DRY RUN — commands will be printed but not executed ==="
    echo
fi

COMMON="--cluster bonete --chip b200 -n 4 --n_shards 1 --cpu 32 --mem 512G -p continual"
EXTRA="training.per_device_batch_size=2"

run_cmd() {
    echo "+ $*"
    if ! $DRY_RUN; then
        "$@"
    fi
    echo
}

# ds_domain / lact (shuffled)
run_cmd uv run theseus submit lact_full_wsd_shuffled-p1 \
    configs/continual/ds_domain/1b/lact_full_wsd_shuffled.yaml \
    $COMMON -g ds_domain_1b $EXTRA

# ds_domain / moe (shuffled)
run_cmd uv run theseus submit moe_full_wsd_shuffled-p1 \
    configs/continual/ds_domain/1b/moe_full_wsd_shuffled.yaml \
    $COMMON -g ds_domain_1b $EXTRA

# ds_domain / transformer (shuffled)
run_cmd uv run theseus submit transformer_full_wsd_shuffled-p1 \
    configs/continual/ds_domain/1b/transformer_full_wsd_shuffled.yaml \
    $COMMON -g ds_domain_1b $EXTRA

# ds_domain / mamba (shuffled)
run_cmd uv run theseus submit mamba_full_wsd_shuffled-p1 \
    configs/continual/ds_domain/1b/mamba_full_wsd_shuffled.yaml \
    $COMMON -g ds_domain_1b $EXTRA

# ds_multilingual / lact (shuffled)
run_cmd uv run theseus submit lact_full_wsd_shuffled-p1 \
    configs/continual/ds_multilingual/1b/lact_full_wsd_shuffled.yaml \
    $COMMON -g ds_multilingual_1b $EXTRA

# ds_multilingual / moe (shuffled)
run_cmd uv run theseus submit moe_full_wsd_shuffled-p1 \
    configs/continual/ds_multilingual/1b/moe_full_wsd_shuffled.yaml \
    $COMMON -g ds_multilingual_1b $EXTRA

# ds_multilingual / transformer (shuffled)
run_cmd uv run theseus submit transformer_full_wsd_shuffled-p1 \
    configs/continual/ds_multilingual/1b/transformer_full_wsd_shuffled.yaml \
    $COMMON -g ds_multilingual_1b $EXTRA

# ds_multilingual / mamba (shuffled)
run_cmd uv run theseus submit mamba_full_wsd_shuffled-p1 \
    configs/continual/ds_multilingual/1b/mamba_full_wsd_shuffled.yaml \
    $COMMON -g ds_multilingual_1b $EXTRA

# cg_safety / lact (shuffled)
run_cmd uv run theseus submit lact_full_wsd_shuffled-p1 \
    configs/data/cl100k/harmfulqa_red_2048.yaml \
    -s configs/data/cl100k/squad_2048.yaml \
    -s configs/data/cl100k/harmfulqa_blue_2048.yaml \
    -s configs/data/cl100k/mmlu_2048.yaml \
    -s configs/continual/cg_safety/1b/lact_full_wsd_shuffled.yaml \
    $COMMON -g cg_safety_1b $EXTRA

# cg_safety / moe (shuffled)
run_cmd uv run theseus submit moe_full_wsd_shuffled-p1 \
    configs/data/cl100k/harmfulqa_red_2048.yaml \
    -s configs/data/cl100k/squad_2048.yaml \
    -s configs/data/cl100k/harmfulqa_blue_2048.yaml \
    -s configs/data/cl100k/mmlu_2048.yaml \
    -s configs/continual/cg_safety/1b/moe_full_wsd_shuffled.yaml \
    $COMMON -g cg_safety_1b $EXTRA

# cg_safety / transformer (shuffled)
run_cmd uv run theseus submit transformer_full_wsd_shuffled-p1 \
    configs/data/cl100k/harmfulqa_red_2048.yaml \
    -s configs/data/cl100k/squad_2048.yaml \
    -s configs/data/cl100k/harmfulqa_blue_2048.yaml \
    -s configs/data/cl100k/mmlu_2048.yaml \
    -s configs/continual/cg_safety/1b/transformer_full_wsd_shuffled.yaml \
    $COMMON -g cg_safety_1b $EXTRA

# cg_safety / mamba (shuffled)
run_cmd uv run theseus submit mamba_full_wsd_shuffled-p1 \
    configs/data/cl100k/harmfulqa_red_2048.yaml \
    -s configs/data/cl100k/squad_2048.yaml \
    -s configs/data/cl100k/harmfulqa_blue_2048.yaml \
    -s configs/data/cl100k/mmlu_2048.yaml \
    -s configs/continual/cg_safety/1b/mamba_full_wsd_shuffled.yaml \
    $COMMON -g cg_safety_1b $EXTRA

echo "=== All 12 shuffled 1b jobs submitted ==="
