architecture:
  dtype:
    param: float32
    activation: bfloat16
  rope: true
  vocab_size: 100288
  dropout: 0.0
  bias: true
  block_size: 2048
  n_layers: 32
  n_embd: 1280
  n_head: 20
optimization:
  lr: 0.0003
  weight_decay: 0.1
  warmup_pct: 0.01
  decay_pct: 0.01
  constant_pct: 0.02
  schedule: cosine_rewarm
  reset_optimizer: false
training:
  batch_size: 512
  per_device_batch_size: -1
  tokens:
  - 6666666666
  - 6666666666
  - 6666666668
  dataset:
  - - name: ccaligned
      rate: 1.0
      style: PMD
      suffix: fr_xx
  - - name: ccaligned
      rate: 1.0
      style: PMD
      suffix: de_de
  - - name: ccaligned
      rate: 1.0
      style: PMD
      suffix: zh_cn
  validation: false
  evaluate: true
  validation_steps: 2048
  skip_first_dataset_validation: false
  fade:
    overlap: 0.0
    curve: linear
eval:
  evaluations:
  - ccaligned_fr_xx
  - ccaligned_de_de
  - ccaligned_zh_cn
logging:
  report_interval: 32
  checkpoint_interval: 4096
  validation_interval: 1024
  wandb: true
job: continual/train/benchmark
request:
  chip: h200
  min_chips: 4
  n_shards: 1
