# uv run theseus submit fp_mid ./configs/forking/fork_placement/mid.yaml -n 2 --chip a6000 --mem 48G -p continual -g fork_placement

architecture:
  rope: true
  n_layers: 16
  n_embd: 1024
  block_size: 512
  dropout: 0.0
  vocab_size: 100288
  max_block_size: 1024
  fork:
  - 6
  - 9
  - 12
  bias: true
  n_head: 16
  use_fork_channel: true
  vram_calib_factor: 1.0
eval:
  evaluations: ["blimp"]
optimization:
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  lr: 0.0003
training:
  batch_size: 512
  per_device_batch_size: -1
  tokens: 6000000000
  warmup_pct: 0.01
  decay_pct: 0.1
  validation: true
  evaluate: false
  dataset:
  - name: fineweb
    rate: 1.0
    style: PMD
    suffix: ''
  validation_steps: 2048
logging:
  report_interval: 32
  checkpoint_interval: 16384
  validation_interval: 2048
  wandb: true
request:
  n_shards: 1
job: thoughtbubbles/train/pretrain
